baseURL = 'https://omarizquierdo.dev/blog/'
canonifyURLs = true
languageCode = 'en-us'
title = 'Omar Izquierdo'
theme = 'poison'

[params]
    brand = "Omar Izquierdo"
    brand_image = "/logo.png" 
    description = "Software Developer"
    dark_mode = false
    favicon = "/logo.png"

    menu = [
        { Name = "About", URL = "/about/", HasChildren = false },
        { Name = "Cibersecurity", URL = "/tags/cibersecurity/", Pre = "Recent", HasChildren = true, Limit = 5 },
        { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
    ]